version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: suri-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./frontend
    container_name: suri-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  streamlit:
    build:
      context: ./streamlit_app
    container_name: suri-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && streamlit run app.py --server.address=0.0.0.0 --server.port=8501"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: suri-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: databox
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
